### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [srozum/film_camera_tester#1]
I see you have no LICENSE file for this project. The default is copyright.

I would suggest releasing the code under the GPL-3.0-or-later or AGPL-3.0-or-later license so that others are encouraged to contribute changes back to your project.

**Comment by srozum** [comment]
Thank you for noticing it. 

The license part is missing because the code published here is a part of the documentation of a hardware, and it's not intended for a development.

However, what license would you recommend for a hardware product?

**Comment by TechnologyClassroom** [comment]
For documentation and hardware, I recommend  Attribution-ShareAlike 4.0 International (CC BY-SA 4.0).

https://creativecommons.org/licenses/by-sa/4.0/

https://spdx.org/licenses/CC-BY-SA-4.0.html

For code, I always recommend GPL-3.0-or-later or AGPL-3.0-or-later.

The documentation, hardware, and code can be licensed separately as well.
